version: "3.9"

services:
  api:
    build: .
    container_name: ${API_CONTAINER_NAME}
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/appdocker-compose logs -f db
      - /app/node_modules

  db:
    image: postgres:15
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: